FROM golang

ADD bisnesscard-server /go/src/github.com/ComputePractice2017/bisnesscard-server 

RUN go get "github.com/gorilla/mux"
RUN go get "github.com/gorilla/handlers"
RUN go get "gopkg.in/gorethink/gorethink.v3"
RUN go install github.com/ComputePractice2017/bisnesscard-server

ENTRYPOINT /go/bin/bisnesscard-server

ENV RETHINKDB_HOST db

EXPOSE 8000